matrix:
    include:
        language: python
        python: "3.7-dev"
        install:
            - pip install -r backend/requirements.txt
        script:
            - pylint
            - pytest
